In [ ]:
import numpy as np

In [ ]:
a = np.array([[0.5, 0.4, 0.8],[-0.7, 0.2, 0.7]])
b= np.array([[0.9],[-0.5]])

In [ ]:
n = a.shape[1]
l = a.shape[0]
print(n)

3


In [ ]:
ac=[]
for i in range(0,n):
  ac.append(a[:,i])

print(ac)

[array([ 0.5, -0.7]), array([0.4, 0.2]), array([0.8, 0.7])]


In [ ]:
result=np.zeros(n)
print(result)

[0. 0. 0.]


In [ ]:
def iterator(A, bn):
  phi = np.dot(A.T, bn)
  max_index = np.argmax(phi, axis=0)
  return max_index[0]

In [ ]:
index_x = []

In [ ]:
def least_square1(t, A, b):
  inv = np.linalg.inv(np.dot(A[:,t].T,A[:,t]))
  x1 = np.dot(A[:,t].T, b)
  x = np.dot(inv,x1)
  return x

In [ ]:
def least_square(t, A, b):
  inv = np.linalg.inv(np.dot(A.T,A))
  x1 = np.dot(A.T, b)
  x = np.dot(inv,x1)
  return x

In [ ]:
def updation(t, b, A, x):
  bn = b - np.dot(A,x)
  #print(b, A[:, t])
  return bn

In [ ]:
r1 = b


In [ ]:
j = iterator(a, r1)
print(j)
i1=j
agu = a[:, j].reshape((2,1))
x = least_square(j, agu, b)
print(x)
r1 = updation(j,b,agu, x)
print(r1)

0
[[1.08108108]]
[[0.35945946]
 [0.25675676]]


In [ ]:
print(a)

[[ 0.5  0.4  0.8]
 [-0.7  0.2  0.7]]


In [ ]:
index_x=[i1]
while (r1 != 0).all():
  j = iterator(a, r1)
  aq = a[:, j].reshape((2,1))
  agu =  np.concatenate((aq, agu), axis=1)
  x = least_square(j, agu, b)
  index_x.append(j)
  r1 = updation(j,b,agu, x)

In [ ]:
print(x)

[[0.41758242]
 [1.13186813]]


In [ ]:
print(index_x)
print(x[1]*0.5+x[0]*0.8)

[0, 2]
[0.9]


In [ ]:
index_x.reverse()

In [ ]:
res = np.zeros((n,1))
for i,j in index_x, range(x.shape[0]):
    res[i]=x[j]
print(res)

[[1.13186813]
 [0.        ]
 [0.41758242]]
